server:
  port: 11001

spring:
  datasource:
    url:  jdbc:mysql://database-1.cuy0kl2qzoel.ap-northeast-2.rds.amazonaws.com?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: alzjelql
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        sql_comments: true

logging:
  level: 
    org.hibernate.type: trace